#theme: jekyll-theme-cayman
#theme: jekyll-theme-midnight
#theme: jekyll-theme-slate
theme: jekyll-theme-minimal

title: "Haruki Yamane's Portfolio"
description: "データサイエンティスト/ブロックチェーンエンジニア。Youtubeでバンドを漁るのが趣味です。Youtube Premiumがないと生きていけません。好きな食べ物は台湾まぜそばと日本酒です。適当に絡んでください。"
logo: img/profile.jpg

twitter:
  username: stkdev
