#theme: jekyll-theme-cayman
#theme: jekyll-theme-midnight
#theme: jekyll-theme-slate
theme: jekyll-theme-minimal

title: "Haruki Yamane's Portfolio"
description: "データサイエンティスト/ブロックチェーンエンジニア"
logo: img/profile.jpg

twitter:
  username: stkdev
